print("        __________")
print('     _ / "Gobble" \\')
print('    / (  "Gobble"  )')
print('   /_/ \__________/')
print("  ++      ____")
print("<(o ) ___(    \\\\")
print(" U\ \/   \\\\    \)")
print("   |   >  ||   //")
print("    \_____//__//")
print("      | |")